service_llm_provider: anthropic-bedrock
service_model_name: anthropic.claude-3-sonnet-20240229-v1:0
rate_limit_per_minute: 60
prompt_tmpl_path: config/prompts.toml
service_llm_gen_config_path: config/claude_gen_configs.yaml

reference_ds_id: llama-duo/coverage_dataset
reference_ds_split: train_summarize
num_samples: 300
seed: 18857
topic: Summarization

gen_workers: 30
rate_limit_on: false

push_synth_ds_to_hf_hub: true
synth_ds_id: chansung/new_summarize_synth_ds3
synth_ds_split: claude3sonnet
synth_ds_append: true
