service_llm_provider: gemini
service_model_name: gemini-1.0-pro
rate_limit_per_minute: 60
prompt_tmpl_path: config/prompts.toml
service_llm_gen_config_path: config/gemini_gen_configs.yaml

reference_ds_id: llama-duo/coverage_dataset
reference_ds_split: train_summarize
num_samples: 500
seed: 2024
topic: Summarization

gen_workers: 4

push_synth_ds_to_hf_hub: true
synth_ds_id: chansung/synth_summarize_dataset
synth_ds_split: train_summarize_gpt4o_2
synth_ds_append: true